# Generated by Django 3.0 on 2022-05-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('price', models.FloatField(verbose_name='price')),
                ('created_at', models.DateField(verbose_name='date')),
                ('num_pages', models.FloatField(verbose_name='num_pages')),
                ('genre', models.CharField(max_length=50, verbose_name='genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('price', models.FloatField(verbose_name='price')),
                ('created_at', models.DateField(verbose_name='date')),
                ('type', models.CharField(max_length=10, verbose_name='type')),
                ('publisher', models.CharField(max_length=50, verbose_name='publisher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
